// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCqF8KQ0VlXGqkU8c4g6Hpp11_04nlZH1g",
    authDomain: "mon-app-40248.firebaseapp.com",
    projectId: "mon-app-40248",
    storageBucket: "mon-app-40248.firebasestorage.app",
    messagingSenderId: "611940366688",
    appId: "1:611940366688:web:96cabd2a6cd59c4fff4605",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TON_API_KEY_ANDROID',
    appId: 'TON_APP_ID_ANDROID',
    messagingSenderId: 'TON_MESSAGING_SENDER_ID',
    projectId: 'TON_PROJECT_ID',
    storageBucket: 'TON_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TON_API_KEY_IOS',
    appId: 'TON_APP_ID_IOS',
    messagingSenderId: 'TON_MESSAGING_SENDER_ID',
    projectId: 'TON_PROJECT_ID',
    storageBucket: 'TON_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );
}
